fix workflow

diff --git a/.github/workflows/pull.yaml b/.github/workflows/pull.yaml
--- a/.github/workflows/pull.yaml
+++ b/.github/workflows/pull.yaml
@@ -10,32 +10,31 @@ on:
             - DEV
 
 jobs:
-    build:
-        runs-on: ubuntu-latest
-        steps:
-            - uses: actions/checkout@v4
-            - name: Setup Docker Buildx
-              uses: docker/setup-buildx-action@v3
-            - name: initialize docker
-              env:
-                AWSLOGIN: ${{ secrets.AWSLOGIN }}
-              run: docker login --username AWS --password $AWSLOGIN 533267032079.dkr.ecr.ap-south-1.amazonaws.com
-            - name: Run Docker Build and push
-              run: |
-                for dir in */; do
-                  cd "$dir"
-                  dir=${dir%/}
-                  echo "Building and pushing $dir"
-                  docker build -t 533267032079.dkr.ecr.ap-south-1.amazonaws.com/opentelemetry/"$dir":${{ github.run_number }} .|| { echo "Docker build failed for $dir"; cd ..; continue; }
-                  docker push 533267032079.dkr.ecr.ap-south-1.amazonaws.com/opentelemetry/"$dir":${{ github.run_number }} || { echo "Docker push failed for $dir"; cd ..; continue; }
-                  cd ..
-                done
-              working-directory: ./src
-              continue-on-error: true
+    # build:
+    #     runs-on: ubuntu-latest
+    #     steps:
+    #         - uses: actions/checkout@v4
+    #         - name: Setup Docker Buildx
+    #           uses: docker/setup-buildx-action@v3
+    #         - name: initialize docker
+    #           env:
+    #             AWSLOGIN: ${{ secrets.AWSLOGIN }}
+    #           run: docker login --username AWS --password $AWSLOGIN 533267032079.dkr.ecr.ap-south-1.amazonaws.com
+    #         - name: Run Docker Build and push
+    #           run: |
+    #             for dir in */; do
+    #               cd "$dir"
+    #               dir=${dir%/}
+    #               echo "Building and pushing $dir"
+    #               docker build -t 533267032079.dkr.ecr.ap-south-1.amazonaws.com/opentelemetry/"$dir":${{ github.run_number }} .|| { echo "Docker build failed for $dir"; cd ..; continue; }
+    #               docker push 533267032079.dkr.ecr.ap-south-1.amazonaws.com/opentelemetry/"$dir":${{ github.run_number }} || { echo "Docker push failed for $dir"; cd ..; continue; }
+    #               cd ..
+    #             done
+    #           working-directory: ./src
+    #           continue-on-error: true
 
     updatek8smanifest:
         runs-on: ubuntu-latest
-        needs: build
         steps:
           - name: Checkout
             uses: actions/checkout@v4
@@ -55,6 +54,7 @@ jobs:
             run: |
               git config --global user.name "Sen"
               git config --global user.email "sen@senworld.in"
+              git remote set-url origin 'https://${{ secrets.GITHUBTOKEN }}@github.com/senworld/OpenTelemetry-Test/'
               git add .
               git commit -m "Updated Kubernetes manifests with new image tags"
               git push 
